name: we_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wechat_camera_picker: ^4.0.1
  wechat_assets_picker: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
